/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vn.viettuts.qlsv.view;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import vn.viettuts.qlsv.entity.Book;
import java.util.ArrayList;
import vn.viettuts.qlsv.dao.BookDao;
/**
 *
 * @author User
 */
public class BookView extends javax.swing.JFrame {

    /**
     * Creates new form SView
     */
    
    private String [] columnNames = new String [] {
            "ID", "Name", "Author", "Year", "Cost", "Type"};
    // định nghĩa dữ liệu mặc định của bẳng book là rỗng
    private Object data = new Object [][] {};
    public BookView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        typeList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        idField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        authorField = new javax.swing.JTextField();
        yearField = new javax.swing.JTextField();
        costField = new javax.swing.JTextField();
        addBookBtn = new javax.swing.JButton();
        editBookBtn = new javax.swing.JButton();
        deleteBookBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        typeSearch = new javax.swing.JComboBox<>();
        searchField = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookTable = new javax.swing.JTable();
        sortBookNameBtn = new javax.swing.JButton();
        sortBookCostBtn = new javax.swing.JButton();
        Type = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        filterButton = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        typeField = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thư viện");

        typeList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Novel", "Newspaper" }));
        typeList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeListActionPerformed(evt);
            }
        });

        jLabel1.setText("ID");

        jLabel2.setText("Name");

        jLabel3.setText("Author");

        jLabel4.setText("Year");

        jLabel5.setText("Cost");

        idField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idFieldActionPerformed(evt);
            }
        });

        addBookBtn.setText("Add");

        editBookBtn.setText("Edit");

        deleteBookBtn.setText("Delete");
        deleteBookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBookBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");

        typeSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "Name", "Author" }));
        typeSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                typeSearchActionPerformed(evt);
            }
        });

        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        bookTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Author", "Year", "Cost", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(bookTable);
        if (bookTable.getColumnModel().getColumnCount() > 0) {
            bookTable.getColumnModel().getColumn(0).setResizable(false);
        }

        sortBookNameBtn.setText("Sort By Name");

        sortBookCostBtn.setText("Sort By Cost");

        Type.setText("Type");

        jLabel7.setText("Search By");

        filterButton.setText("Filter");

        jLabel6.setText("Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(addBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(editBookBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(deleteBookBtn)
                                .addGap(18, 18, 18)
                                .addComponent(clearBtn)
                                .addGap(20, 20, 20))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearField)
                                    .addComponent(authorField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Type, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(72, 72, 72)
                                        .addComponent(filterButton))
                                    .addComponent(nameField, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                                    .addComponent(idField)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(costField)
                                    .addComponent(typeField))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(sortBookNameBtn)
                                .addGap(55, 55, 55)
                                .addComponent(sortBookCostBtn)
                                .addContainerGap(129, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(buttonSearch)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(typeList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Type)
                            .addComponent(filterButton))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(idField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(authorField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(yearField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(costField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sortBookNameBtn)
                            .addComponent(sortBookCostBtn))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(typeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addBookBtn)
                            .addComponent(deleteBookBtn)
                            .addComponent(clearBtn)
                            .addComponent(editBookBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(typeSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch))
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idFieldActionPerformed
        // TODO add your handling code here
        
    }//GEN-LAST:event_idFieldActionPerformed

    private void deleteBookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBookBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBookBtnActionPerformed

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        // TODO add your handling code here:
       
        
        
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void typeSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeSearchActionPerformed

    private void typeListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_typeListActionPerformed
    
    
    
    public void showListBooks(List<Book> list) {
        int size = list.size();
        // với bảng bookTable có 5 cột, 
        // khởi tạo mảng 2 chiều books, trong đó:
        // số hàng: là kích thước của list book 
        // số cột: là 5
        Object [][] books = new Object[size][6];
        for (int i = 0; i < size; i++) {
            books[i][0] = list.get(i).getId();
            books[i][1] = list.get(i).getName();
            books[i][2] = list.get(i).getAuthor();
            books[i][3] = list.get(i).getYear();
            books[i][4] = list.get(i).getCost();
            books[i][5] = list.get(i).getType();

        }
        bookTable.setModel(new DefaultTableModel(books, columnNames));
    }
    
    
    public void fillBookFromSelectedRow() {
        // lấy chỉ số của hàng được chọn 
        int row = bookTable.getSelectedRow();
        if (row >= 0) {
            idField.setText(bookTable.getModel().getValueAt(row, 0).toString());
            nameField.setText(bookTable.getModel().getValueAt(row, 1).toString());
            authorField.setText(bookTable.getModel().getValueAt(row, 2).toString());
            yearField.setText(bookTable.getModel().getValueAt(row, 3).toString());
            costField.setText(bookTable.getModel().getValueAt(row, 4).toString());
            typeField.setText(bookTable.getModel().getValueAt(row, 5).toString());
            // enable Edit and Delete buttons
            editBookBtn.setEnabled(true);
            deleteBookBtn.setEnabled(true);
            // disable Add button
            addBookBtn.setEnabled(false);
        }
    }
    
    public void clearBookInfo() {
        idField.setText("");
        nameField.setText("");
        authorField.setText("");
        yearField.setText("");
        costField.setText("");
        typeField.setText("");
        // disable Edit and Delete buttons
        editBookBtn.setEnabled(false);
        deleteBookBtn.setEnabled(false);
        // enable Add button
        addBookBtn.setEnabled(true);
    }
    
    /**
     * hiện thị thông tin book
     * 
     * @param book
     */
    public void showBook(Book book) {
        idField.setText("" + book.getId());
        nameField.setText(book.getName());
        authorField.setText("" + book.getAuthor());
        yearField.setText(""+book.getYear());
        costField.setText("" + book.getCost());
        typeField.setText("" + book.getType());
        // enable Edit and Delete buttons
        editBookBtn.setEnabled(true);
        deleteBookBtn.setEnabled(true);
        // disable Add button
        addBookBtn.setEnabled(false);
    }
    
    
    public Book getBookInfo() {
        // validate book
        if (!validateName() || !validateAuthor() || !validateYear() || !validateCost() || !validateType()) {
            return null;
        }
        try {
            Book book = new Book();
            if (idField.getText() != null && !"".equals(idField.getText())) {
                book.setId(Integer.parseInt(idField.getText()));
            }
            book.setName(nameField.getText().trim());
            book.setAuthor(authorField.getText().trim());
            book.setYear(Integer.parseInt(yearField.getText().trim()));
            book.setCost(Float.parseFloat(costField.getText().trim()));
            book.setType(typeField.getText().trim());
            return book;
        } catch (Exception e) {
            showMessage(e.getMessage());
        }
        return null;
    }
    
    
    private boolean validateType() {
        String type = nameField.getText();
        if (type == null || "".equals(type.trim())) {
            typeField.requestFocus();
            showMessage("Type không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateName() {
        String name = nameField.getText();
        if (name == null || "".equals(name.trim())) {
            nameField.requestFocus();
            showMessage("Name không được trống.");
            return false;
        }
        return true;
    }
    
    private boolean validateYear() {
        try {
            int year = Integer.parseInt(yearField.getText().trim());
            if (year < 0 || year >2023) {
                yearField.requestFocus();
                showMessage("Year không hợp lệ, year nên lớn hơn 0 va bé hơn 2023");
                return false;
            }
        } catch (Exception e) {
            yearField.requestFocus();
            showMessage("Year không hợp lệ!");
            return false;
        }
        return true;    }
    
    private boolean validateAuthor() {
           String author = authorField.getText();
        if (author == null || "".equals(author.trim())) {
            authorField.requestFocus();
            showMessage("Author không được trống.");
            return false;
        }
        return true;

    }
    
    private boolean validateCost() {
        try {
            Float cost = Float.parseFloat(costField.getText().trim());
            if (cost < 0) {
                costField.requestFocus();
                showMessage("Cost không hợp lệ, cost nên lớn hơn 0");
                return false;
            }
        } catch (Exception e) {
            costField.requestFocus();
            showMessage("Cost không hợp lệ!");
            return false;
        }
        return true;
    }
    
    
    public void findByName(List<Book> list){
        String ten= searchField.getText();
        List<Book> listFind= new ArrayList<>();
        for(int i=0;i<list.size();i++){
            Book temp= list.get(i);
            if(temp.getName().equalsIgnoreCase(ten)){
                listFind.add(temp);
            }
        }
        
        if(listFind.size() > 0){
            showMessage("OK");
        }else{
            showMessage("Khong tim thay");
        }
        showListBooks(listFind);
    }
    
    public void findByAuthor(List<Book> list){
        String author= searchField.getText();
        List<Book> listFind= new ArrayList<>();
        for(int i=0;i<list.size();i++){
            Book temp= list.get(i);
            if(temp.getAuthor().equalsIgnoreCase(author)){
                listFind.add(temp);
                
            }
        }
        
        if(listFind.size() > 0){
            showMessage("OK");
        }else{
            showMessage("Khong tim thay");
        }
        showListBooks(listFind);
    }
    public void Search(List<Book> list){
        String type= typeSearch.getSelectedItem().toString();
        if(type=="Name"){
            findByName(list);
        }else if(type=="Author"){
            findByAuthor(list);
        }
    }
    
    public void filter(List<Book> list){
        String type= typeList.getSelectedItem().toString();
        List<Book> listFind= new ArrayList<>();
        if(type != "All"){
        for(int i=0;i<list.size();i++){
            Book temp= list.get(i);
            if(temp.getType().equalsIgnoreCase(type)){
                listFind.add(temp);
                
            }
        }
        
        if(listFind.size() > 0){
            showMessage("OK");
        }
        showListBooks(listFind);
        }
        
        else{
            showListBooks(list);
        }
    }
    public void showMessage(String message) {
        JOptionPane.showMessageDialog(this, message);
    }
    
    public void addSearchBookListener(ActionListener listener) {
        buttonSearch.addActionListener(listener);
    }
    
    public void addAddBookListener(ActionListener listener) {
        addBookBtn.addActionListener(listener);
    }
    
    public void addEdiBookListener(ActionListener listener) {
        editBookBtn.addActionListener(listener);
    }
    
    public void addDeleteBookListener(ActionListener listener) {
        deleteBookBtn.addActionListener(listener);
    }
    
    public void addClearListener(ActionListener listener) {
        clearBtn.addActionListener(listener);
    }
    
    public void addSortBookCostListener(ActionListener listener) {
        sortBookCostBtn.addActionListener(listener);
    }
    
    public void addSortBookNameListener(ActionListener listener) {
        sortBookNameBtn.addActionListener(listener);
    }
    
    public void addListBookSelectionListener(ListSelectionListener listener) {
        bookTable.getSelectionModel().addListSelectionListener(listener);
    }
    public void addFilterBookListener(ActionListener listener) {
        filterButton.addActionListener(listener);
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Type;
    private javax.swing.JButton addBookBtn;
    private javax.swing.JTextField authorField;
    private javax.swing.JTable bookTable;
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton clearBtn;
    private javax.swing.JTextField costField;
    private javax.swing.JButton deleteBookBtn;
    private javax.swing.JButton editBookBtn;
    private javax.swing.JButton filterButton;
    private javax.swing.JTextField idField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField;
    private javax.swing.JTextField searchField;
    private javax.swing.JButton sortBookCostBtn;
    private javax.swing.JButton sortBookNameBtn;
    private javax.swing.JTextField typeField;
    private javax.swing.JComboBox<String> typeList;
    private javax.swing.JComboBox<String> typeSearch;
    private javax.swing.JTextField yearField;
    // End of variables declaration//GEN-END:variables
}

